sudo: required
services:
  - docker
install:
  - docker run --privileged -v `pwd`:/pwd/ -it robermorales/singularity-centos singularity create -s 500 image.img
  - docker run --privileged -v `pwd`:/pwd/ -it robermorales/singularity-centos singularity bootstrap     image.img singularity.def
script:
  - docker run --privileged -v `pwd`:/pwd/ -it robermorales/singularity-centos singularity test          image.img
after_script:
  - docker run --privileged -v `pwd`:/pwd/ -it robermorales/singularity-centos gzip image.img
  - docker run --privileged -v `pwd`:/pwd/ -it robermorales/singularity-centos sha512sum image.* > sha512sums
addons:
  artifacts: true
